In [2]:
import tensorflow as tf

# ----------- 准备
unq_categories = ["music", "movie", "finance", "game", "military", "history"]
# 这一层负责将string转化为int型id
id_mapping_layer = tf.keras.layers.StringLookup(vocabulary=unq_categories)

emb_layer = tf.keras.layers.Embedding(
    # 多加一维是为了处理，当输入不包含在unq_categories的情况
    input_dim=len(unq_categories) + 1,
    output_dim=4)  # output_dim指明映射向量的长度

In [3]:
# ----------- Embedding
cate_input = ["music", "movie"]  # [batch_size,1]的string型"文章分类"向量
cate_ids = id_mapping_layer(cate_input)  # string型输入的“文章分类”映射成int型id


In [6]:
cate_embeddings = emb_layer(cate_ids)

In [7]:
cate_embeddings

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.04506437,  0.00835569,  0.00836945, -0.03334794],
       [ 0.03020823, -0.03062726,  0.0229771 , -0.01514376]],
      dtype=float32)>

In [4]:
# Importing the library
import tensorflow as tf
# Initializing the input
data = tf.constant([[1, 2, 3], [4, 5, 6]])
# Printing the input
print('data: ', data)
# Calculating result
res = tf.IndexedSlices(data, [0])
# Printing the result
print('res: ', res)


data:  tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
res:  IndexedSlices(indices=[0], values=tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32))
